### ISSUE TITLE
Unable to install opentelemetry-instrumentation-redis

### ISSUE THREAD

**Issue by ringsaturn** [mitsuhiko/rye#662] opened 2024-02-16 10:38 UTC
### Steps to Reproduce

```bash
rye add --pre opentelemetry-instrumentation-redis
```

### Expected Result

Like pip `pip install opentelemetry-instrumentation-redis` can normally install it.

### Actual Result

```
error: did not find package 'opentelemetry-instrumentation-redis'
```

### Version Info

```
rye 0.24.0
commit: 0.24.0 (8d56aa18a 2024-02-15)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true
```

**Comment by mitsuhiko** [comment] 2024-02-16 11:34
Probably duplicate of #654

**Comment by ringsaturn** [comment] 2024-02-16 11:39
I try another way to add, and it works:

```bash
rye add --pre 'opentelemetry-instrumentation-redis==0.43b0'
```

Seems need to declare a version?

**Closed** 2024-02-16 11:40 UTC

**Comment by mitsuhiko** [comment] 2024-02-16 11:52
Yeah this is a bug that needs solving.
