### ISSUE TITLE
Python version pinning inside pyproject.toml

### ISSUE THREAD

**Issue by shroominic** [mitsuhiko/rye#524] opened 2023-12-18 06:06 UTC
I think it would be nice to give people the option to pin python versions using the pyproject.toml instead of a seperate .python-version file. I dont want to remove the file but just have a setting in the rye config.toml or a check if its already pinned inside the pyproject to not force everyone to have a pinned .python-version file. I personally prefer having less .files in my repo and more single config files.

It could look something like this inside the pyproject.toml :
```
[tool.rye]
python-version = "cpython@3.12.0"
```

**Comment by rmarquis** [comment] 2023-12-20 08:27
>  it would be nice to give people the option 

I'd argue that having a single option and enforcing it is prefereable, as opposed to allowing flexibility (based on preferences only) that leads to a messy situation across projects, with no clear way of doing something.

I'm also not a fan of having a `.python-version` file, but I do reckon it is also compatible with the  `actions/setup-python` GitHub action, which makes me think it is the de-facto standard and should be preferred (and ideally, the only way of doing it).

**Comment by mitsuhiko** [comment] 2024-01-15 21:01
The question is if there is also then an expectation if this value is used if you `rye install` something. I'm a bit worried about putting too much rye specific stuff into the wider ecosystem.

**Comment by mitsuhiko** [comment] 2024-01-21 19:27
This is a duplicate of #96

**Closed by mitsuhiko** 2024-01-21 19:27 UTC
