### ISSUE TITLE
ipython cannot location installed modules when installed as a tool

### ISSUE THREAD

**Issue by JLHasson** [mitsuhiko/rye#635] opened 2024-02-10 21:28 UTC
### Steps to Reproduce

```
$ rye tools install ipython
$ ipython
In [1]: ! python -m pip install requests
In [2]: import requests
ModuleNotFoundError: No module named 'requests'
```

I also tried the following which produced the same result:
```
rye add requests
# or
rye tools install requests
```

### Expected Result

import requests would succeed

### Actual Result

```
$ ipython
In [1]: ! python -m pip install requests
In [2]: import requests
ModuleNotFoundError: No module named 'requests'
```

### Version Info

```
$ rye --version
rye 0.21.0
commit: 0.21.0 (2e0e02459 2024-02-03)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true
```

**Comment by mitsuhiko** [comment] 2024-02-11 09:59
That works as intended because at the moment the tool is installed into a separate virtualenv. There is currently no convenient way to install something into that virtualenv. This is how you would do it:

```
~/.rye/self/bin/pip --python ~/.rye/tools/ipython/bin/python install package-name
```

Closing as duplicate of #473

**Closed by mitsuhiko** 2024-02-11 09:59 UTC
