### ISSUE TITLE
rye add pyqlib faild

### ISSUE THREAD

**Issue by meritozh** [mitsuhiko/rye#162] opened 2023-05-15 08:43 UTC
### Steps to Reproduce

1.  install rye
2. rye pin 3.8
3. rye sync
4. rye add pyqlib

### Expected Result

succeed

### Actual Result

Error: did not find package 'pyqlib'

### Version Info

```
rye 0.1.0
commit: unknown (55d02a7f4 2023-05-15)
platform: macos (aarch64)
self-python: cpython@3.10
```

**Comment by mitsuhiko** [comment] 2023-05-15 09:55
Going to close this because this is not a bug. You have an aarch64 machine, the package in question does not exist for aarch64 (m1/m2) but only for x86_64. I opened an issue for adding interpreters of different architectures (#163).

To solve this for now you would need to manually download an `x86_64` build of Python, unpack it and then link it. Eg:

```
curl -L https://github.com/indygreg/python-build-standalone/releases/download/20221106/cpython-3.8.15%2B20221106-x86_64-apple-darwin-pgo-full.tar.zst | tar xf -
mv python ~/.rye/py/cpython-64@3.8.15
```

And then pin to that version:

```
rye pin cpython-64@3.8.15
```

**Closed by mitsuhiko** 2023-05-15 09:55 UTC
