### ISSUE TITLE
`rye add langchain` results in an old version

### ISSUE THREAD

**Issue by andrewg-xyz** [mitsuhiko/rye#305] opened 2023-06-10 00:21 UTC
### Steps to Reproduce

1. `rye add langchain`

### Expected Result

Added langchain~=0.0.195 as regular dependency

** 0.0.195 is current published version in PyPI [ref](https://pypi.org/project/langchain/)

### Actual Result

![image](https://github.com/mitsuhiko/rye/assets/46836330/58453bd3-2442-4d3d-a172-b1780243cc4d)

### Version Info

```
rye 0.6.0
commit: 0.6.0 (2023-06-03)
platform: macos (aarch64)
self-python: cpython@3.10
symlink support: true
```

(while I understand rye brings the toolchain)
```
python3 --version
Python 3.11.3
```

**Comment by ischaojie** [comment] 2023-06-10 03:27
langchain (0.0.195) requires Python >=3.8.1,<4.0, you should make sure `requires-python>=3.8.1` at least.

**Comment by mitsuhiko** [comment] 2023-06-21 17:24
Closing this. From what I can tell this is working as intended.

**Closed by mitsuhiko** 2023-06-21 17:24 UTC
