### ISSUE TITLE
Comply with the XDG Base Directory Specification

### ISSUE THREAD

**Issue by doolio** [mitsuhiko/rye#426] opened 2023-08-28 10:51 UTC
Put rye's `config.toml` under `${XDG_CONFIG_HOME:-${HOME}/.config}/rye`.
Put rye's other data under `${XDG_DATA_HOME:-${HOME}/.local/share}/rye`.

**Comment by mitsuhiko** [comment] 2023-09-08 20:34
Duplicate of #316. See the last comment there for why I do not want to do this.

**Closed by mitsuhiko** 2023-09-08 20:34 UTC

**Comment by doolio** [comment] 2023-09-09 08:13
Apologies for not checking if it was raised already.
