### ISSUE TITLE
Allow custom location for .venv

### ISSUE THREAD

**Issue by PhilipVinc** [mitsuhiko/rye#371] opened 2023-07-17 17:45 UTC
I wish there was a way to specify a folder where rye should keep all virtual environments, and provide a simple command to allow activating that environment.

For example, this could be an env variable or configuration flag such as 
```
RYE_VIRTUALENV_DEPOT="~/Documents/rye-envs
```
and they could be stored in a directory names as `NAME-HHH` where `NAME` is the name of the project and `HHH` is some hash of the path, for example.
(I am aware that this means that changing the path of the project would make rye create a new venv... but I don't have great alternatives to mind).

Why?

I keep all of my clones of repositories where I work on in a dropbox folder that is synced between my laptop and my workstation. That way I don't need to remind myself about committing my work every time I switch computer, and I have my stashes with me at all times.

However, my workstation and laptop have different architectures (Mac and linux) so I cannot keep the virtual environments in the same folder.

**Comment by mitsuhiko** [comment] 2023-07-18 15:55
One thing I was considering was adding a way to have `.venv` be a symlink to managed location. I am not sure if getting rid of `.venv` is a good idea in general as it means that you need to consider different setups again which makes documentation and everything around it harder. But I do understand the general desire.

One way to square this would be to have a flag in the rye config that turns on out-of-tree virtualenvs where only a symlink is placed and the actual virtualenv is placed elsewhere.

**Comment by PhilipVinc** [comment] 2023-07-18 20:46
A symlink would not be compatible with my _personal_ setup, because I sync those folders with dropbox (which will kill the symlink). In general, I would prefer to keep the virtual environment outside of folders I sync on the internet but of course that's just my personal point of view.

Out of curiosity, what would be the added complication of having a global depot for the virtual environments, beside having to add and maintain a sort of `rye activate` function that activates the _local_ virtual environment ?

**Comment by zhuang1234** [comment] 2023-08-28 03:36
Why don't you try to get dropbox to ignore this folder?

**Comment by PhilipVinc** [comment] 2023-08-28 12:27
I can't, because I have one such folder in every python project I work on (~several tens) and would have to do this on every device.

**Comment by doolio** [comment] 2023-08-29 16:43
> I use direnv + pyenv to setup my projects.
> ````shell
> cat .envrc
> layout pyenv-venv 3.11.2 netket
> ````
Shouldn't it just be `layout pyenv 3.11.2`? Why `pyenv-venv`? In any case, `rye` removes the need of `pyenv`. FYI, as an alternative to `pyenv` there is [`asdf`](https://asdf-vm.com/) or [`rtx`](https://github.com/jdx/rtx) which use `pyenv` under the hood for python but can be used for other languages/tools.

Alternatives to `rye` that allows both centrally located environments and environments in the project root that you did not mention above are [`hatch`](https://hatch.pypa.io/latest/) and [`pdm`](https://pdm.fming.dev/latest/). Unlike `rye` though they don't install different python versions for you so you would still need something like `pyenv`. Unlike Poetry and Hatch, but like `rye` PDM is not limited to a specific build backend; users have the freedom to choose any PEP621 compliant build backend they prefer.

+1 for `rye` to allow centrally located environments (perhaps as the default) and environments in the project root.

**Comment by mitsuhiko** [comment] 2024-01-20 19:19
I'm closing this. I have no desire to add support for other locations into the tool in an attempt to standardize what I believe the correct  behavior is (the one true location).

**Closed by mitsuhiko** 2024-01-20 19:19 UTC

**Comment by simonw** [comment] 2024-02-04 19:51
Just dropped by to request this same feature, for the same reason: I keep hundreds of my Python projects in a Dropbox folder (purely as insurance against someone stealing my laptop before I've run `git commit` on them) and I use `pipenv` to manage virtual environments purely because I want those environments to live outside of Dropbox, so I don't end up backing up hundreds of environments to Dropbox unnecessarily.

**Comment by mitsuhiko** [comment] 2024-02-04 23:23
@simonw I wonder if it would make more sense if rye had an option where it automatically sets the necessary flags on `.venv` to prevent synching. Eg: `com.dropbox.ignored` in case of dropbox. Then you can leave those files where they are, but `.venv` won't end up replicated to dropbox.

**Comment by mitsuhiko** [comment] 2024-03-12 21:17
@dedeswim how do you do this with `node_modules`?

**Comment by dedeswim** [comment] 2024-03-12 21:19
Thanks for the reply.

I'm not a node user, so it's the first time I've faced this issue.

What I do with e.g., Conda, is to set CONDA_HOME to some place on the local SSD, but of course this is a bit different from what happens with rye.

**Comment by dedeswim** [comment] 2024-03-12 21:37
Unfortunately I wasn't the one setting up the computer (as it is half-managed by the university I work at), but, if it were my choice, I agree that I would set things up so that everything would be on the same disk.

The advantage of the non-local disk where I usually store code is that it is synchronised across machines and is redundantly backed up. This makes it easy to jump between machines (in case resources on one are busy to run the experiments I need), and at the same time I don't need to worry about losing my code (in case I forget to commit). Instead, on the local disk I can store "disposable" files, like a virtual environment.

Anyways, thanks for your time thinking about this, I will think of another way to use rye even without this feature because I honestly really like it!

**Comment by tomerha** [comment] 2024-05-05 08:27
In case it matters, I unfortunately find `rye` unusable for some of my setups where I have the project workdir mounted on a remote server over sshfs and then the `.venv` realpath moves between local and remote executions :(

It would be really nice to support this feature.

**Comment by mitsuhiko** [comment] 2024-05-08 22:13
@tomerha how do you deal with this in node?

**Comment by tomerha** [comment] 2024-05-09 08:26
> @tomerha how do you deal with this in node?

I don't use node, just Python 😇

With Python, for now I use `hatch` which works for me since the venv is external

**Comment by mitsuhiko** [comment] 2024-05-09 09:26
I understand that it works, but supporting it has a lot of downsides requiring explicit configuration to discover the venv. It means that every tool needs to start learning where that venv is.

Since the same issue must exist in node they either must have found a solution there, the issue is not pressing enough or it’s unresolved and there must be some discussion around it.

**Comment by PhilipVinc** [comment] 2024-05-09 09:29
What do you mean by `every tool needs to start learning where that venv is.`? 

Isn't it enough for rye to know where the venv is, and the rye's python shims are enough to get this sorted out? Or you mean that `VIRTUAL_ENV` variable must also be correctly set..?

**Comment by mitsuhiko** [comment] 2024-05-09 09:35
It's not enough if just rye knows where the venv is, because the goal is that you stuff "just works" across toolings. If we establish `.venv` as the canonical location of a virtualenv, then any tooling can just magically automatically work for as long as the venv is in a synched state.  This means editors can just rely on being able to auto discover it.

Today a lot of the bad DX from python comes from tools accidentally falling back to global python or requiring manual configuration for which virtualenv to use resulting in a lot of extra cost to be paid everywhere.

**Comment by tomerha** [comment] 2024-05-09 10:35
I'm not that familiar with npm or node, but from what I understood the similar issue is with `node_modules`?

I didn't try myself but it look with node it can be manually worked around using bind mounts (see https://github.com/npm/npm/issues/7120#issuecomment-166586939).

However this solution doesn't work with rye since when the venv is created it tries to create a symlink to the Python interpreter and this fails since symlinks on sshfs don't behave as expected (e.g with `-o follow_symlinks` they're translated to regular file mirrors from the server side).

**Comment by mitsuhiko** [comment] 2024-05-10 08:42
Rye should not manipulate owners so in theory that step is not necessary to begin with. What however might be an issue is that the same trick will run into rye’s behavior to re-create the venv. That might require further changes.

Maybe the right way forward here would be to make an issue for precisely the situation we need to solve for and to see what solutions we can come up with.

**Comment by phromo** [comment] 2024-05-20 20:50
> @tomerha how do you deal with this in node?

FYI in node there is an alternative to npm, `pnpm` and it solves this by creating symlinks inside `node_modules` to `~/.pnpm/`

**Comment by phromo** [comment] 2024-11-19 06:56
FYI I have switched to uv where this is more or less a non problem.
