### ISSUE TITLE
Support for private repositories

### ISSUE THREAD

**Issue by ollz272** [mitsuhiko/rye#60] opened 2023-04-27 19:18 UTC
Currently in poetry you can do something like:

```toml
[[tool.poetry.source]]
name = "my_source"
url = "..."

[tool.poetry.dependencies]
my-package = { version = "=1.0.0", source = "my_source" }
```
to support getting packages from a private repository.

However this doesn't seem to work with rye out the box. Is there a way to do this with rye, or is development needed?

**Comment by mitsuhiko** [comment] 2023-04-27 21:22
That does not work today. It's effectively a duplicate of #36.

**Closed by mitsuhiko** 2023-04-27 21:22 UTC
